site_name: ğŸ’œ
site_description: ğŸ“š
site_author: ğŸ±
theme: bootstrap386

nav:
  - ğŸ‘¾ : index.md
  - ğŸ“:
    - âšˆ ğŸ€‡ ğŸ€™ ğŸ€ ğŸ‚¡ ğŸ¤: chapter_1.md
    - âš‰ ğŸ€ˆ ğŸ€š ğŸ€‘ ğŸ‚¢ ğŸ¥: chapter_2.md
    - âš† ğŸ€‰ ğŸ€› ğŸ€’ ğŸ‚£ ğŸ¦: chapter_3.md
  - â•: toBeContinued.md