site_name: Windows 386
site_description: ğŸ“š
site_author: ğŸ±

theme:
  name: bootstrap386

nav:
  - BIOS: index.md
  - Home: bio.md
  - Files:
    - âšˆ ğŸ€‡ ğŸ€™ ğŸ€ ğŸ‚¡ ğŸ¤: chapter_1.md
    - âš‰ ğŸ€ˆ ğŸ€š ğŸ€‘ ğŸ‚¢ ğŸ¥: chapter_2.md
    - âš† ğŸ€‰ ğŸ€› ğŸ€’ ğŸ‚£ ğŸ¦: chapter_3.md
  - Help: toBeContinued.md