site_name: Cirno's Perfect Eigo Class â‘¨
site_description: ğŸ“š
site_author: ğŸ±

# theme:
#   # name: bootstrap386
#   name: bootstrap

theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

nav:
  # - BIOS: index.md
  - Home: index.md
  - Funky:
    - âšˆ ASSIGNMENT_1: chapter_1.md
    - âš‰ ASSIGNMENT_2: chapter_2.md
    - âš† ASSIGNMENT_3: chapter_3.md
    - âš‡ ASSIGNMENT_4: chapter_4.md
    - âšˆ ASSIGNMENT_5: chapter_5.md
  - Baka: toBeContinued.md

plugins: ['search']

extra:
    version: 0.4.0

copyright: Copyright &copy; 2024 Zane Loeng